// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import {act} from '@testing-library/react';

import type {PropertyFieldOption} from '@mattermost/types/properties';
import type {BoardsPropertyField} from '@mattermost/types/properties_board';

import {Client4} from 'mattermost-redux/client';

import {renderHookWithContext, waitFor} from 'tests/react_testing_utils';

import {
    isCreatePending,
    isDeletePending,
    isOptionNameTaken,
    isPendingId,
    newPendingBoardField,
    newPendingId,
    stripPendingOptionIds,
    useBoardPropertyFields,
    ValidationWarningNameRequired,
    ValidationWarningNameTaken,
    ValidationWarningNameUnique,
} from './board_attributes_utils';

describe('board_attributes_utils', () => {
    describe('newPendingId / isPendingId', () => {
        test('newPendingId returns a string prefixed with pending_', () => {
            expect(newPendingId()).toMatch(/^pending_/);
        });

        test('newPendingId returns unique ids on each call', () => {
            const ids = new Set([newPendingId(), newPendingId(), newPendingId()]);
            expect(ids.size).toBe(3);
        });

        test('isPendingId is true for ids generated by newPendingId', () => {
            expect(isPendingId(newPendingId())).toBe(true);
        });

        test('isPendingId is false for non-pending ids', () => {
            expect(isPendingId('')).toBe(false);
            expect(isPendingId('real-server-id-abc')).toBe(false);
            expect(isPendingId('pending')).toBe(false);
            expect(isPendingId('pending-with-dash')).toBe(false);
        });
    });

    describe('stripPendingOptionIds', () => {
        test('returns undefined for undefined input', () => {
            expect(stripPendingOptionIds(undefined)).toBeUndefined();
        });

        test('returns empty array for empty input', () => {
            expect(stripPendingOptionIds([])).toEqual([]);
        });

        test('replaces pending ids with empty strings', () => {
            const pendingId = newPendingId();
            const options: PropertyFieldOption[] = [
                {id: pendingId, name: 'Pending option'},
            ];

            const result = stripPendingOptionIds(options);
            expect(result).toEqual([{id: '', name: 'Pending option'}]);
        });

        test('leaves real server ids untouched', () => {
            const options: PropertyFieldOption[] = [
                {id: 'real-server-id-abc123', name: 'Saved option', color: 'red'},
            ];

            const result = stripPendingOptionIds(options);
            expect(result).toEqual([{id: 'real-server-id-abc123', name: 'Saved option', color: 'red'}]);
        });

        test('handles mixed pending and real ids in one array', () => {
            const pendingId = newPendingId();
            const options: PropertyFieldOption[] = [
                {id: 'real-1', name: 'A'},
                {id: pendingId, name: 'B'},
                {id: 'real-2', name: 'C'},
            ];

            const result = stripPendingOptionIds(options);
            expect(result).toEqual([
                {id: 'real-1', name: 'A'},
                {id: '', name: 'B'},
                {id: 'real-2', name: 'C'},
            ]);
        });

        test('preserves option properties beyond id (name, color)', () => {
            const pendingId = newPendingId();
            const options: PropertyFieldOption[] = [
                {id: pendingId, name: 'X', color: 'blue'},
            ];

            const result = stripPendingOptionIds(options);
            expect(result?.[0]).toEqual({id: '', name: 'X', color: 'blue'});
        });
    });

    describe('newPendingBoardField', () => {
        test('returns a field with a pending id', () => {
            const field = newPendingBoardField({name: 'Priority'});
            expect(isPendingId(field.id)).toBe(true);
        });

        test('defaults to text type', () => {
            const field = newPendingBoardField({name: 'Priority'});
            expect(field.type).toBe('text');
        });

        test('zeroes out create_at/delete_at/update_at to mark as create-pending', () => {
            const field = newPendingBoardField({name: 'Priority'});
            expect(field.create_at).toBe(0);
            expect(field.delete_at).toBe(0);
            expect(field.update_at).toBe(0);
            expect(isCreatePending(field)).toBe(true);
        });

        test('sets group_id to "boards" and target_type to "system"', () => {
            const field = newPendingBoardField({name: 'Priority'});
            expect(field.group_id).toBe('boards');
            expect(field.target_type).toBe('system');
            expect(field.object_type).toBe('post');
        });

        test('assigns pending ids to each option in attrs.options', () => {
            const field = newPendingBoardField({
                name: 'Status',
                type: 'select',
                attrs: {
                    sort_order: 0,
                    options: [
                        {id: 'whatever', name: 'Todo'},
                        {id: '', name: 'Done'},
                    ],
                },
            });

            const options = field.attrs.options ?? [];
            expect(options).toHaveLength(2);
            expect(options.every((o) => isPendingId(o.id))).toBe(true);

            // ids must be unique across options so chips remain individually keyable
            const ids = new Set(options.map((o) => o.id));
            expect(ids.size).toBe(2);
        });

        test('does not touch attrs.options when not provided', () => {
            const field = newPendingBoardField({name: 'Title'});
            expect(field.attrs.options).toBeUndefined();
        });
    });

    describe('isCreatePending / isDeletePending', () => {
        test('isCreatePending true when create_at and delete_at are both 0', () => {
            expect(isCreatePending({id: 'x', create_at: 0, delete_at: 0})).toBe(true);
        });

        test('isCreatePending false when create_at is non-zero (already saved)', () => {
            expect(isCreatePending({id: 'x', create_at: 1234, delete_at: 0})).toBe(false);
        });

        test('isDeletePending true when item was saved (create_at > 0) and is now flagged for delete (delete_at > 0)', () => {
            expect(isDeletePending({create_at: 1234, delete_at: 5678})).toBe(true);
        });

        test('isDeletePending false for never-saved items, even if delete_at is set', () => {
            // An item that was added and removed before saving is neither create-pending nor delete-pending
            expect(isDeletePending({create_at: 0, delete_at: 5678})).toBe(false);
        });
    });

    describe('isOptionNameTaken', () => {
        const options: PropertyFieldOption[] = [
            {id: '1', name: 'Todo'},
            {id: '2', name: 'In Progress'},
            {id: '3', name: 'Done'},
        ];

        test('returns true when candidate matches another option (case-insensitive)', () => {
            expect(isOptionNameTaken('todo', options)).toBe(true);
            expect(isOptionNameTaken('TODO', options)).toBe(true);
            expect(isOptionNameTaken('Todo', options)).toBe(true);
        });

        test('returns true when candidate has whitespace padding matching another option', () => {
            expect(isOptionNameTaken('  Todo  ', options)).toBe(true);
        });

        test('returns false when candidate is unique', () => {
            expect(isOptionNameTaken('Blocked', options)).toBe(false);
        });

        test('excludes a given option from the conflict check (used during rename)', () => {
            // Renaming "Todo" → "Todo" should not flag itself as a conflict
            expect(isOptionNameTaken('Todo', options, options[0])).toBe(false);
        });

        test('still flags conflicts against other options when excluding', () => {
            // Renaming option 1 to "Done" should still conflict with option 3
            expect(isOptionNameTaken('Done', options, options[0])).toBe(true);
        });
    });
});

describe('useBoardPropertyFields', () => {
    jest.useFakeTimers();
    const getFields = jest.spyOn(Client4, 'getPropertyFields');
    const patchField = jest.spyOn(Client4, 'patchPropertyField');
    const deleteField = jest.spyOn(Client4, 'deletePropertyField');
    const createField = jest.spyOn(Client4, 'createPropertyField');

    const baseField: BoardsPropertyField = {
        id: 'field-id',
        name: 'field',
        type: 'text',
        group_id: 'boards',
        object_type: 'post',
        create_at: 1736541716295,
        delete_at: 0,
        update_at: 0,
        created_by: '',
        updated_by: '',
        target_id: '',
        target_type: 'system',
        attrs: {sort_order: 0},
    };

    const systemField: BoardsPropertyField = {...baseField, id: 'system-status', name: 'Status', protected: true, attrs: {sort_order: 5}};
    const field0: BoardsPropertyField = {...baseField, id: 'field-0', name: 'Priority', attrs: {sort_order: 0}};
    const field1: BoardsPropertyField = {...baseField, id: 'field-1', name: 'Owner', type: 'user', attrs: {sort_order: 1}};
    const field2: BoardsPropertyField = {...baseField, id: 'field-2', name: 'Due date', type: 'date', attrs: {sort_order: 2}};

    beforeEach(() => {
        getFields.mockReset();
        patchField.mockReset();
        deleteField.mockReset();
        createField.mockReset();

        // Return the fields deliberately out of order so the hook's sort is exercised.
        getFields.mockResolvedValue([field2, field0, systemField, field1]);
    });

    async function renderLoaded() {
        const rendered = renderHookWithContext(() => useBoardPropertyFields(), {});

        act(() => {
            jest.runAllTimers();
        });
        rendered.rerender();

        await waitFor(() => {
            const [, read] = rendered.result.current;
            expect(read.loading).toBe(false);
        });

        return rendered;
    }

    test('should load the fields with protected ones first and the rest by sort order', async () => {
        const {result} = await renderLoaded();

        const [fields, read] = result.current;
        expect(getFields).toHaveBeenCalledWith('boards', 'post', 'system');
        expect(read.error).toBeUndefined();
        expect(fields.order).toEqual([systemField.id, field0.id, field1.id, field2.id]);
        expect(fields.data[field1.id]).toBe(field1);
        expect(fields.warnings).toBeUndefined();
    });

    test('should warn when two pending fields share a name, ignoring case', async () => {
        const {result, rerender} = await renderLoaded();

        act(() => {
            const [fields,,, ops] = result.current;
            ops.update({...fields.data[field0.id], name: 'OWNER'});
        });
        rerender();

        const [fields,, pendingIO] = result.current;
        expect(pendingIO.hasChanges).toBe(true);
        expect(fields.warnings).toEqual({
            [field0.id]: {name: ValidationWarningNameUnique},
            [field1.id]: {name: ValidationWarningNameUnique},
        });
    });

    test('should warn when a pending name collides with a saved field, unless that field is being deleted', async () => {
        const {result, rerender} = await renderLoaded();

        // Free up the name "Owner" in the pending set, then claim it for another field. The pending
        // set has no duplicate, but the saved set still has "Owner" on field1, so the name is taken.
        act(() => {
            const [fields,,, ops] = result.current;
            ops.update({...fields.data[field1.id], name: 'Assignee'});
        });
        rerender();
        act(() => {
            const [fields,,, ops] = result.current;
            ops.update({...fields.data[field0.id], name: 'owner'});
        });
        rerender();

        const [fields1,, pendingIO] = result.current;
        expect(pendingIO.hasChanges).toBe(true);
        expect(fields1.warnings).toEqual({[field0.id]: {name: ValidationWarningNameTaken}});

        // Once the field that holds the saved name is pending deletion, the conflict is gone.
        act(() => {
            const [,,, ops] = result.current;
            ops.delete(field1.id);
        });
        rerender();

        const [fields2] = result.current;
        expect(fields2.data[field1.id].delete_at).not.toBe(0);
        expect(fields2.warnings).toBeUndefined();
    });

    test('should give a new field a unique name and immediately drop it again when deleted before saving', async () => {
        const {result, rerender} = await renderLoaded();

        act(() => {
            const [,,, ops] = result.current;
            ops.create({name: 'Priority'});
        });
        rerender();

        const [fields1] = result.current;
        const createdId = fields1.order.find((id) => isPendingId(id))!;
        expect(fields1.data[createdId].name).toBe('Priority (2)');
        expect(fields1.data[createdId].attrs.sort_order).toBe(4);
        expect(fields1.warnings).toBeUndefined();

        act(() => {
            const [,,, ops] = result.current;
            ops.delete(createdId);
        });
        rerender();

        const [fields2,, pendingIO] = result.current;
        expect(fields2.data[createdId]).toBeUndefined();
        expect(fields2.order).not.toContain(createdId);
        expect(pendingIO.hasChanges).toBe(false);
    });

    test('should require a name and skip validation for protected fields', async () => {
        const {result, rerender} = await renderLoaded();

        act(() => {
            const [fields,,, ops] = result.current;
            ops.update({...fields.data[field2.id], name: ''});
            ops.update({...fields.data[systemField.id], name: ''});
        });
        rerender();

        const [fields] = result.current;
        expect(fields.warnings).toEqual({[field2.id]: {name: ValidationWarningNameRequired}});
    });

    test('should commit an edit and clear pending changes when the server accepts it', async () => {
        const {result, rerender} = await renderLoaded();

        act(() => {
            const [fields,,, ops] = result.current;
            ops.update({...fields.data[field0.id], name: 'Severity'});
        });
        rerender();

        const [fields, readIO, pendingIO] = result.current;
        patchField.mockResolvedValue({...fields.data[field0.id]});

        await act(async () => {
            const data = await pendingIO.commit();
            if (data) {
                readIO.setData(data);
            }
            jest.runAllTimers();
            rerender();
        });

        await waitFor(() => {
            const [,, pending] = result.current;
            expect(pending.saving).toBe(false);
        });

        expect(patchField).toHaveBeenCalledTimes(1);
        expect(patchField).toHaveBeenCalledWith('boards', 'post', field0.id, {name: 'Severity', type: 'text', attrs: {sort_order: 0}});
        expect(deleteField).not.toHaveBeenCalled();
        expect(createField).not.toHaveBeenCalled();

        const [fieldsAfter,, pendingAfter] = result.current;
        expect(pendingAfter.hasChanges).toBe(false);
        expect(pendingAfter.error).toBeUndefined();
        expect(fieldsAfter.data[field0.id].name).toBe('Severity');
        expect(fieldsAfter.errors).toBeUndefined();
    });

    test('should surface a per-field error and keep the change pending when the server rejects it', async () => {
        const {result, rerender} = await renderLoaded();

        act(() => {
            const [fields,,, ops] = result.current;
            ops.update({...fields.data[field0.id], name: 'Severity'});
        });
        rerender();

        const [, readIO, pendingIO] = result.current;
        const serverError = new Error('name already exists');
        patchField.mockRejectedValue(serverError);

        await act(async () => {
            const data = await pendingIO.commit();
            if (data) {
                readIO.setData(data);
            }
            jest.runAllTimers();
            rerender();
        });

        await waitFor(() => {
            const [,, pending] = result.current;
            expect(pending.saving).toBe(false);
        });

        const [fieldsAfter,, pendingAfter] = result.current;
        expect(pendingAfter.hasChanges).toBe(true);
        expect(pendingAfter.error).toBeDefined();
        expect(pendingAfter.error?.message).toBe('error processing operations');
        expect((pendingAfter.error?.cause as Record<string, unknown>)[field0.id]).toBe(serverError);
        expect(fieldsAfter.data[field0.id].name).toBe('Severity');
    });
});
